// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindMaxX() {
  return window['go']['main']['App']['FindMaxX']();
}

export function FindMaxY() {
  return window['go']['main']['App']['FindMaxY']();
}

export function GetAllProfiles() {
  return window['go']['main']['App']['GetAllProfiles']();
}

export function GetSelectedProfile() {
  return window['go']['main']['App']['GetSelectedProfile']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTempCurve(arg1) {
  return window['go']['main']['App']['GetTempCurve'](arg1);
}

export function GetTempHistory() {
  return window['go']['main']['App']['GetTempHistory']();
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function ResetBuffer() {
  return window['go']['main']['App']['ResetBuffer']();
}

export function ShiftTempBuffer(arg1) {
  return window['go']['main']['App']['ShiftTempBuffer'](arg1);
}
